### PR TITLE
Change build system

### PR DESCRIPTION
**Pull request by matheus23**
This is my stab at #168 
I've made some bold changes like removing the justfile and moving built files into a subdirectory `dist/`. (publishing would now work via `yarn publish-{alpha/latest}`).
Some users will have to update their builds (we would have to do that with fission-suite/drive).
But for most users nothing should change, except that importing webnative from a directory now is slightly easier.

I've tested some `npm publish --dry-run`s. I've ignored pretty much every file that's not included in the previous version, except for the changelog, which would now be included.
Also, previously the top-level README would overwrite the README generated by typedoc, so that changed, too. (typedoc files are now in `docs/` instead of top-level).

This is somewhat of an experiment, the goal being to making some things easier. However, it's a breaking change, soo... I guess if at all, better now than later? :smile: 

Let me know what you think :pray:

### CODE REVIEW

**Review by icidasset — APPROVED** [review]
Oops, just now saw this PR 😄 Looks good! 👏 
I'll merge this since I'll be working on the docs.

**Comment by matheus23** [comment]
>  I'll merge this since I'll be working on the docs.

Should I merge this or let you do it? Or was there perhaps something not quite right with the PR?

**Comment by icidasset** [comment]
> > I'll merge this since I'll be working on the docs.
> 
> Should I merge this or let you do it? Or was there perhaps something not quite right with the PR?

You can merge them 👍 I ended up not having time to test these changes.

**Comment by matheus23** [comment]
I made some more changes. This is the difference between the files which would be published on master and the files that would be publish on this branch:

<details>
<summary>Published files diff</summary>

```diff
--- dry-run-master.txt  2021-02-11 18:58:53.358242882 +0100
+++ dry-run-branch.txt  2021-02-11 18:54:28.369542545 +0100
@@ -1,57 +1,211 @@
-apps.d.ts
-apps.js
-apps.js.map
-auth.d.ts
-auth.js
-auth.js.map
-common/api.d.ts
-common/api.js
-common/api.js.map
-common/arrbufs.d.ts
-common/arrbufs.js
-common/arrbufs.js.map
-common/async.d.ts
-common/async.js
-common/async.js.map
-common/base64.d.ts
-common/base64.js
-common/base64.js.map
-common/blob.d.ts
-common/blob.js
-common/blob.js.map
-common/cid-log.d.ts
-common/cid-log.js
-common/cid-log.js.map
-common/crypto.d.ts
-common/crypto.js
-common/crypto.js.map
-common/debug.d.ts
-common/debug.js
-common/debug.js.map
-common/hex.d.ts
-common/hex.js
-common/hex.js.map
-common/index.d.ts
-common/index.js
-common/index.js.map
-common/type-checks.d.ts
-common/type-checks.js
-common/type-checks.js.map
-common/types.d.ts
-common/types.js
-common/types.js.map
-common/util.d.ts
-common/util.js
-common/util.js.map
-data-root.d.ts
-data-root.js
-data-root.js.map
-did.d.ts
-did.js
-did.js.map
-dns/index.d.ts
-dns/index.js
-dns/index.js.map
+CHANGELOG.md
+dist/apps.d.ts
+dist/apps.js
+dist/apps.js.map
+dist/auth.d.ts
+dist/auth.js
+dist/auth.js.map
+dist/common/api.d.ts
+dist/common/api.js
+dist/common/api.js.map
+dist/common/arrbufs.d.ts
+dist/common/arrbufs.js
+dist/common/arrbufs.js.map
+dist/common/async.d.ts
+dist/common/async.js
+dist/common/async.js.map
+dist/common/base64.d.ts
+dist/common/base64.js
+dist/common/base64.js.map
+dist/common/blob.d.ts
+dist/common/blob.js
+dist/common/blob.js.map
+dist/common/cid-log.d.ts
+dist/common/cid-log.js
+dist/common/cid-log.js.map
+dist/common/crypto.d.ts
+dist/common/crypto.js
+dist/common/crypto.js.map
+dist/common/debug.d.ts
+dist/common/debug.js
+dist/common/debug.js.map
+dist/common/hex.d.ts
+dist/common/hex.js
+dist/common/hex.js.map
+dist/common/index.d.ts
+dist/common/index.js
+dist/common/index.js.map
+dist/common/type-checks.d.ts
+dist/common/type-checks.js
+dist/common/type-checks.js.map
+dist/common/types.d.ts
+dist/common/types.js
+dist/common/types.js.map
+dist/common/util.d.ts
+dist/common/util.js
+dist/common/util.js.map
+dist/data-root.d.ts
+dist/data-root.js
+dist/data-root.js.map
+dist/did.d.ts
+dist/did.js
+dist/did.js.map
+dist/dns/index.d.ts
+dist/dns/index.js
+dist/dns/index.js.map
+dist/errors.d.ts
+dist/errors.js
+dist/errors.js.map
+dist/filesystem.d.ts
+dist/filesystem.js
+dist/filesystem.js.map
+dist/fs/bare/file.d.ts
+dist/fs/bare/file.js
+dist/fs/bare/file.js.map
+dist/fs/bare/tree.d.ts
+dist/fs/bare/tree.js
+dist/fs/bare/tree.js.map
+dist/fs/base/file.d.ts
+dist/fs/base/file.js
+dist/fs/base/file.js.map
+dist/fs/base/tree.d.ts
+dist/fs/base/tree.js
+dist/fs/base/tree.js.map
+dist/fs/filesystem.d.ts
+dist/fs/filesystem.js
+dist/fs/filesystem.js.map
+dist/fs/index.d.ts
+dist/fs/index.js
+dist/fs/index.js.map
+dist/fs/link.d.ts
+dist/fs/link.js
+dist/fs/link.js.map
+dist/fs/metadata.d.ts
+dist/fs/metadata.js
+dist/fs/metadata.js.map
+dist/fs/path.d.ts
+dist/fs/path.js
+dist/fs/path.js.map
+dist/fs/protocol/basic.d.ts
+dist/fs/protocol/basic.js
+dist/fs/protocol/basic.js.map
+dist/fs/protocol/index.d.ts
+dist/fs/protocol/index.js
+dist/fs/protocol/index.js.map
+dist/fs/protocol/private/index.d.ts
+dist/fs/protocol/private/index.js
+dist/fs/protocol/private/index.js.map
+dist/fs/protocol/private/mmpt.d.ts
+dist/fs/protocol/private/mmpt.js
+dist/fs/protocol/private/mmpt.js.map
+dist/fs/protocol/private/namefilter.d.ts
+dist/fs/protocol/private/namefilter.js
+dist/fs/protocol/private/namefilter.js.map
+dist/fs/protocol/private/types.d.ts
+dist/fs/protocol/private/types.js
+dist/fs/protocol/private/types.js.map
+dist/fs/protocol/private/types/check.d.ts
+dist/fs/protocol/private/types/check.js
+dist/fs/protocol/private/types/check.js.map
+dist/fs/protocol/public/index.d.ts
+dist/fs/protocol/public/index.js
+dist/fs/protocol/public/index.js.map
+dist/fs/protocol/public/skeleton.d.ts
+dist/fs/protocol/public/skeleton.js
+dist/fs/protocol/public/skeleton.js.map
+dist/fs/protocol/public/types.d.ts
+dist/fs/protocol/public/types.js
+dist/fs/protocol/public/types.js.map
+dist/fs/root/tree.d.ts
+dist/fs/root/tree.js
+dist/fs/root/tree.js.map
+dist/fs/semver.d.ts
+dist/fs/semver.js
+dist/fs/semver.js.map
+dist/fs/types.d.ts
+dist/fs/types.js
+dist/fs/types.js.map
+dist/fs/types/check.d.ts
+dist/fs/types/check.js
+dist/fs/types/check.js.map
+dist/fs/v1/PrivateFile.d.ts
+dist/fs/v1/PrivateFile.js
+dist/fs/v1/PrivateFile.js.map
+dist/fs/v1/PrivateHistory.d.ts
+dist/fs/v1/PrivateHistory.js
+dist/fs/v1/PrivateHistory.js.map
+dist/fs/v1/PrivateTree.d.ts
+dist/fs/v1/PrivateTree.js
+dist/fs/v1/PrivateTree.js.map
+dist/fs/v1/PublicFile.d.ts
+dist/fs/v1/PublicFile.js
+dist/fs/v1/PublicFile.js.map
+dist/fs/v1/PublicHistory.d.ts
+dist/fs/v1/PublicHistory.js
+dist/fs/v1/PublicHistory.js.map
+dist/fs/v1/PublicTree.d.ts
+dist/fs/v1/PublicTree.js
+dist/fs/v1/PublicTree.js.map
+dist/index.cjs.js
+dist/index.cjs.js.map
+dist/index.d.ts
+dist/index.es5.js
+dist/index.es5.js.map
+dist/index.js
+dist/index.js.map
+dist/index.umd.js
+dist/index.umd.js.map
+dist/ipfs/basic.d.ts
+dist/ipfs/basic.js
+dist/ipfs/basic.js.map
+dist/ipfs/config.d.ts
+dist/ipfs/config.js
+dist/ipfs/config.js.map
+dist/ipfs/constants.d.ts
+dist/ipfs/constants.js
+dist/ipfs/constants.js.map
+dist/ipfs/encoded.d.ts
+dist/ipfs/encoded.js
+dist/ipfs/encoded.js.map
+dist/ipfs/index.d.ts
+dist/ipfs/index.js
+dist/ipfs/index.js.map
+dist/ipfs/types.d.ts
+dist/ipfs/types.js
+dist/ipfs/types.js.map
+dist/ipfs/util.d.ts
+dist/ipfs/util.js
+dist/ipfs/util.js.map
+dist/keystore/basic.d.ts
+dist/keystore/basic.js
+dist/keystore/basic.js.map
+dist/keystore/config.d.ts
+dist/keystore/config.js
+dist/keystore/config.js.map
+dist/keystore/index.d.ts
+dist/keystore/index.js
+dist/keystore/index.js.map
+dist/lobby/blocklist.d.ts
+dist/lobby/blocklist.js
+dist/lobby/blocklist.js.map
+dist/lobby/index.d.ts
+dist/lobby/index.js
+dist/lobby/index.js.map
+dist/setup.d.ts
+dist/setup.js
+dist/setup.js.map
+dist/setup/internal.d.ts
+dist/setup/internal.js
+dist/setup/internal.js.map
+dist/ucan.d.ts
+dist/ucan.js
+dist/ucan.js.map
+dist/ucan/internal.d.ts
+dist/ucan/internal.js
+dist/ucan/internal.js.map
+dist/ucan/permissions.d.ts
+dist/ucan/permissions.js
+dist/ucan/permissions.js.map
 docs/assets/css/main.css
 docs/assets/images/icons.png
 docs/assets/images/icons@2x.png
@@ -78,158 +232,6 @@
 docs/modules/lobby.html
 docs/modules/setup.html
 docs/modules/ucan.html
-errors.d.ts
-errors.js
-errors.js.map
-filesystem.d.ts
-filesystem.js
-filesystem.js.map
-fs/bare/file.d.ts
-fs/bare/file.js
-fs/bare/file.js.map
-fs/bare/tree.d.ts
-fs/bare/tree.js
-fs/bare/tree.js.map
-fs/base/file.d.ts
-fs/base/file.js
-fs/base/file.js.map
-fs/base/tree.d.ts
-fs/base/tree.js
-fs/base/tree.js.map
-fs/filesystem.d.ts
-fs/filesystem.js
-fs/filesystem.js.map
-fs/index.d.ts
-fs/index.js
-fs/index.js.map
-fs/link.d.ts
-fs/link.js
-fs/link.js.map
-fs/metadata.d.ts
-fs/metadata.js
-fs/metadata.js.map
-fs/path.d.ts
-fs/path.js
-fs/path.js.map
-fs/protocol/basic.d.ts
-fs/protocol/basic.js
-fs/protocol/basic.js.map
-fs/protocol/index.d.ts
-fs/protocol/index.js
-fs/protocol/index.js.map
-fs/protocol/private/index.d.ts
-fs/protocol/private/index.js
-fs/protocol/private/index.js.map
-fs/protocol/private/mmpt.d.ts
-fs/protocol/private/mmpt.js
-fs/protocol/private/mmpt.js.map
-fs/protocol/private/namefilter.d.ts
-fs/protocol/private/namefilter.js
-fs/protocol/private/namefilter.js.map
-fs/protocol/private/types.d.ts
-fs/protocol/private/types.js
-fs/protocol/private/types.js.map
-fs/protocol/private/types/check.d.ts
-fs/protocol/private/types/check.js
-fs/protocol/private/types/check.js.map
-fs/protocol/public/index.d.ts
-fs/protocol/public/index.js
-fs/protocol/public/index.js.map
-fs/protocol/public/skeleton.d.ts
-fs/protocol/public/skeleton.js
-fs/protocol/public/skeleton.js.map
-fs/protocol/public/types.d.ts
-fs/protocol/public/types.js
-fs/protocol/public/types.js.map
-fs/root/tree.d.ts
-fs/root/tree.js
-fs/root/tree.js.map
-fs/semver.d.ts
-fs/semver.js
-fs/semver.js.map
-fs/types.d.ts
-fs/types.js
-fs/types.js.map
-fs/types/check.d.ts
-fs/types/check.js
-fs/types/check.js.map
-fs/v1/PrivateFile.d.ts
-fs/v1/PrivateFile.js
-fs/v1/PrivateFile.js.map
-fs/v1/PrivateHistory.d.ts
-fs/v1/PrivateHistory.js
-fs/v1/PrivateHistory.js.map
-fs/v1/PrivateTree.d.ts
-fs/v1/PrivateTree.js
-fs/v1/PrivateTree.js.map
-fs/v1/PublicFile.d.ts
-fs/v1/PublicFile.js
-fs/v1/PublicFile.js.map
-fs/v1/PublicHistory.d.ts
-fs/v1/PublicHistory.js
-fs/v1/PublicHistory.js.map
-fs/v1/PublicTree.d.ts
-fs/v1/PublicTree.js
-fs/v1/PublicTree.js.map
-index.cjs.js
-index.cjs.js.map
-index.d.ts
-index.es5.js
-index.es5.js.map
-index.js
-index.js.map
-index.umd.js
-index.umd.js.map
-ipfs/basic.d.ts
-ipfs/basic.js
-ipfs/basic.js.map
-ipfs/config.d.ts
-ipfs/config.js
-ipfs/config.js.map
-ipfs/constants.d.ts
-ipfs/constants.js
-ipfs/constants.js.map
-ipfs/encoded.d.ts
-ipfs/encoded.js
-ipfs/encoded.js.map
-ipfs/index.d.ts
-ipfs/index.js
-ipfs/index.js.map
-ipfs/types.d.ts
-ipfs/types.js
-ipfs/types.js.map
-ipfs/util.d.ts
-ipfs/util.js
-ipfs/util.js.map
-keystore/basic.d.ts
-keystore/basic.js
-keystore/basic.js.map
-keystore/config.d.ts
-keystore/config.js
-keystore/config.js.map
-keystore/index.d.ts
-keystore/index.js
-keystore/index.js.map
-lobby/blocklist.d.ts
-lobby/blocklist.js
-lobby/blocklist.js.map
-lobby/index.d.ts
-lobby/index.js
-lobby/index.js.map
+LICENSE
 package.json
-README.md
-setup.d.ts
-setup.js
-setup.js.map
-setup/internal.d.ts
-setup/internal.js
-setup/internal.js.map
-ucan.d.ts
-ucan.js
-ucan.js.map
-ucan/internal.d.ts
-ucan/internal.js
-ucan/internal.js.map
-ucan/permissions.d.ts
-ucan/permissions.js
-ucan/permissions.js.map
+README.md
```

</details>

It's mostly things moving from top-level to `dist`.

I've checked that the source files included are actually all still included, and they are.

Still, once this is published, some consumers have to change how they consume webnative. E.g. drive will have to copy `node_modules/webnative/dist/index.js` instead of `node_modules/webnative/index.js`.

Sorry for bumping this again. In the process of testing this a little more I figured out some more things I could improve. :sweat_smile:

**Comment by icidasset** [comment]
Nice, looking good! The only thing missing from list are the minified files you made, I think?

**Comment by matheus23** [comment]
The `index.umd.js` file is now minified. There's no un-minified version of it anymore.
Do you think we should have two versions? A `.min` version and a normal one?

**Comment by icidasset** [comment]
Ah gotcha. Yeah, both a minified version and normal version would be ideal.

**Comment by matheus23** [comment]
So now the umd build creates three files:
* `index.umd.js`
* `index.umd.min.js` (minified)
* `index.umd.min.js.gz` (minified, gzipped)

```sh
$ wc -c dist/index.umd.min.js.gz 
157463 dist/index.umd.min.js.gz
```

Should be ready to merge now :+1:

**Review by walkah — APPROVED** [review]
tenor-71159003

Look good! Thanks for tackling this!

**Review by icidasset — APPROVED** [review]

**Pull request merged**
