### PR TITLE
improved apps API

### PR DESCRIPTION
**Pull request by matheus23**
I've changed the apps API after some dogfooding via implementing the dashboard.

### CODE REVIEW

**Review by icidasset — APPROVED** [review]
Nice 👌 This ready to merge?

**Comment by matheus23** [comment]
There's an issue with the `DELETE /apps/{app ID}` route, so I'd like to wait until that's resolved (but it's *likely* that that's a server issue).

I'm fairly sure that there will not be any more changes, but I'd like to have at least one working run through everything :)

I'll ping again, when it's ready.

**Comment by matheus23** [comment]
Turns out all of the requests are technically working, even though there's a CORS issue. I'd say this is ready to merge :)

**Comment by icidasset** [comment]
Sounds good, merging this @matheus23 
Publishing `0.23.0` later today.

**Pull request merged**
