### PR TITLE
Put files in MMPT & do file revisions properly

### PR DESCRIPTION
**Pull request by dholms**
## Problem
Our IPFS Gateway is not grabbing all of the content needed for a user's FS. This is because file content is not being correctly added to the MMPT on the private side.

## Solution
- Put file contents in MMPT
- properly revision files & contents in MMPT

Also:
- add `members()` method to MMPT for debugging
- add `localOnly` flag for filesystem for local testing purposes

### CODE REVIEW

**Comment by dholms** [comment]
To test:
- Run quotes app locally
- use `webnative@0.18.0-alpha`
- login to Quotes & create a new account
- add a couple quotes, navigate etc
- wait for DNS to propagate (can take awhile)
- _Exit out of the original quotes app_ (we don't want the second page to make a browser hop, we want to ensure that the gateway has all of the needed content
- open quotes app in a separate browser (or incognito window)
- login to quotes app & see if content loads

**Comment by icidasset** [comment]
Updated https://quotes.fission.app to v0.19-alpha, seems to be working smoothly now 🎉

**Comment by icidasset** [comment]
@dholms Should we merge this? 👀

**Comment by dholms** [comment]
Oops, didn't mean to leave it as a draft. Yup! It's good to go whenever :ok_hand:

**Pull request merged**
