### PR TITLE
Added proofs to jwt for app routes

### PR DESCRIPTION
**Pull request by nathanmalishev**
## Bug Fix

Added proofs to JWT for app routes. See  #104

### CODE REVIEW

**Review by icidasset — APPROVED** [review]
Thank you!

**Comment by icidasset** [comment]
Give me a thumbs up if this is ready to go, and I'll merge & publish a new version 👀

**Comment by nathanmalishev** [comment]
👍  @icidasset

**Comment by icidasset** [comment]
Published as `v0.18.1`

**Pull request merged**
