### PR TITLE
Add a rule to disallow semicolons

### PR DESCRIPTION
**Pull request by bgins**
## Summary

This PR fixes/implements the following **bugs/features**

* [x] Add linter rule to disallow semicolons

We tend to not use semicolons. This makes it official.

## Test plan (required)

Run `npm run lint` and you will see some warnings for some errant semicolons, mostly in tests.

## After Merge
* [ ] Does this change invalidate any docs or tutorials? _If so ensure the changes needed are either made or recorded_
* [ ] Does this change require a release to be made? Is so please create and deploy the release

### CODE REVIEW

**Comment by matheus23** [comment]
What does enabling this rule mean for the few cases in which ASI doesn't work?

**Comment by bgins** [comment]
That's a good question. The `never` setting makes some exceptions: https://eslint.org/docs/rules/semi#never. We have one case that looks like their example:

https://github.com/fission-suite/webnative/blob/f1340a00fbae9c89c322d41dccd7506c2c9ceb9c/src/auth.ts#L37

The `never` rule also allows semicolons in old-school for loops:

https://github.com/fission-suite/webnative/blob/f1340a00fbae9c89c322d41dccd7506c2c9ceb9c/src/common/hex.ts#L10

Are there other cases where we want a semicolon that we should try out?

**Review by matheus23 — APPROVED** [review]
This answers my question! :)

> Are there other cases where we want a semicolon that we should try out?

I remember this case from the dashboard source code:

```js
const unhighlight = async event => {
  event.preventDefault()
  this.classList.remove("dropping")
};

["dragleave", "drop"].map(ev => this.addEventListener(ev, unhighlight));
["dragenter", "dragover"].map(ev => this.addEventListener(ev, highlight));
```

But I they've got that covered:

> except to disambiguate statements beginning with `[`, `(`, `/`, `+`, or `-`

So :+1: :+1:

**Review by matheus23 — APPROVED** [review]

**Comment by matheus23** [comment]
I think we can just merge this, right? I'll push the button for now.

**Comment by bgins** [comment]
Yep, we can. Thanks! :pray:

**Pull request merged**
